// In-memory graph dataset providing full CognoDB Cypher parity for demo/offline execution

export const MOCK_CATEGORIES = [
  { id: 'cat-fundamentals', name: 'Core Fundamentals' },
  { id: 'cat-frontend', name: 'Frontend Development' },
  { id: 'cat-backend', name: 'Backend & API Architecture' },
  { id: 'cat-data', name: 'Data Science & AI' },
  { id: 'cat-devops', name: 'DevOps & Cloud' },
  { id: 'cat-database', name: 'Databases & Storage' },
];

export const MOCK_SKILLS = [
  {
    id: 'prog-fund',
    name: 'Programming Fundamentals',
    description: 'Control flow, variables, algorithms, data structures, and problem-solving basics.',
    difficulty: 'Beginner',
    categoryId: 'cat-fundamentals',
  },
  {
    id: 'git',
    name: 'Version Control (Git)',
    description: 'Branching, merging, pull requests, commit history, and GitHub workflows.',
    difficulty: 'Beginner',
    categoryId: 'cat-fundamentals',
  },
  {
    id: 'html-css',
    name: 'HTML5 & Modern CSS',
    description: 'Semantic HTML layout, Flexbox, CSS Grid, responsive design, and web accessibility.',
    difficulty: 'Beginner',
    categoryId: 'cat-frontend',
  },
  {
    id: 'javascript',
    name: 'JavaScript (ES6+)',
    description: 'Promises, async/await, closures, prototypes, DOM manipulation, and event loop.',
    difficulty: 'Intermediate',
    categoryId: 'cat-frontend',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    description: 'Static typing, interfaces, generics, type inference, and compiler configuration.',
    difficulty: 'Intermediate',
    categoryId: 'cat-frontend',
  },
  {
    id: 'react',
    name: 'React.js',
    description: 'Components, hooks, state management, virtual DOM, and component lifecycles.',
    difficulty: 'Intermediate',
    categoryId: 'cat-frontend',
  },
  {
    id: 'testing-frontend',
    name: 'Frontend Testing',
    description: 'Unit testing with Jest, component testing with React Testing Library, and E2E with Playwright.',
    difficulty: 'Advanced',
    categoryId: 'cat-frontend',
  },
  {
    id: 'nodejs',
    name: 'Node.js Runtime',
    description: 'Event-driven asynchronous I/O, event emitters, modules, and server-side JavaScript.',
    difficulty: 'Intermediate',
    categoryId: 'cat-backend',
  },
  {
    id: 'express',
    name: 'Express.js Framework',
    description: 'HTTP routing, middleware pattern, request parsing, authentication, and error handling.',
    difficulty: 'Intermediate',
    categoryId: 'cat-backend',
  },
  {
    id: 'rest-apis',
    name: 'REST API Architecture',
    description: 'Resource design, HTTP methods, status codes, OpenAPI specs, and serialization.',
    difficulty: 'Intermediate',
    categoryId: 'cat-backend',
  },
  {
    id: 'sql',
    name: 'Relational Databases & SQL',
    description: 'Tables, keys, foreign joins, indexes, transactions, normalization, and SQL querying.',
    difficulty: 'Intermediate',
    categoryId: 'cat-database',
  },
  {
    id: 'graph-db',
    name: 'Graph Databases & Cypher',
    description: 'Nodes, relationships, property graph model, Cypher pattern matching, and graph algorithms.',
    difficulty: 'Advanced',
    categoryId: 'cat-database',
  },
  {
    id: 'python',
    name: 'Python Programming',
    description: 'Pythonic idioms, data structures, object-oriented programming, and package ecosystem.',
    difficulty: 'Beginner',
    categoryId: 'cat-data',
  },
  {
    id: 'data-analysis',
    name: 'Data Analysis with Pandas',
    description: 'DataFrames, data cleaning, aggregation, exploratory data analysis, and visualization.',
    difficulty: 'Intermediate',
    categoryId: 'cat-data',
  },
  {
    id: 'statistics',
    name: 'Statistics & Probability',
    description: 'Hypothesis testing, distributions, regression, variance, and inferential statistics.',
    difficulty: 'Intermediate',
    categoryId: 'cat-data',
  },
  {
    id: 'machine-learning',
    name: 'Machine Learning',
    description: 'Supervised and unsupervised learning, decision trees, Scikit-Learn, and model evaluation.',
    difficulty: 'Advanced',
    categoryId: 'cat-data',
  },
  {
    id: 'deep-learning',
    name: 'Deep Learning & Neural Networks',
    description: 'Convolutional/Recurrent neural networks, PyTorch/TensorFlow, backpropagation, and transformers.',
    difficulty: 'Advanced',
    categoryId: 'cat-data',
  },
  {
    id: 'linux',
    name: 'Linux Systems Administration',
    description: 'Bash scripting, file permissions, process management, networking basics, and SSH.',
    difficulty: 'Intermediate',
    categoryId: 'cat-devops',
  },
  {
    id: 'docker',
    name: 'Docker Containerization',
    description: 'Dockerfiles, container images, Docker Compose multi-container environments, and volumes.',
    difficulty: 'Intermediate',
    categoryId: 'cat-devops',
  },
  {
    id: 'ci-cd',
    name: 'CI/CD Pipelines',
    description: 'Automated building, testing, integration, and continuous deployment workflows (GitHub Actions).',
    difficulty: 'Advanced',
    categoryId: 'cat-devops',
  },
  {
    id: 'cloud-fundamentals',
    name: 'Cloud Infrastructure (AWS/GCP)',
    description: 'Compute instances, serverless, VPC networking, cloud storage, IAM security, and deployment.',
    difficulty: 'Advanced',
    categoryId: 'cat-devops',
  },
];

// Prerequisites: skillId REQUIRES prereqId
export const MOCK_PREREQUISITES = [
  { skillId: 'javascript', prereqId: 'prog-fund' },
  { skillId: 'html-css', prereqId: 'prog-fund' },
  { skillId: 'typescript', prereqId: 'javascript' },
  { skillId: 'react', prereqId: 'javascript' },
  { skillId: 'react', prereqId: 'html-css' },
  { skillId: 'testing-frontend', prereqId: 'react' },
  { skillId: 'testing-frontend', prereqId: 'typescript' },
  { skillId: 'nodejs', prereqId: 'javascript' },
  { skillId: 'express', prereqId: 'nodejs' },
  { skillId: 'rest-apis', prereqId: 'express' },
  { skillId: 'graph-db', prereqId: 'sql' },
  { skillId: 'python', prereqId: 'prog-fund' },
  { skillId: 'data-analysis', prereqId: 'python' },
  { skillId: 'statistics', prereqId: 'python' },
  { skillId: 'machine-learning', prereqId: 'data-analysis' },
  { skillId: 'machine-learning', prereqId: 'statistics' },
  { skillId: 'deep-learning', prereqId: 'machine-learning' },
  { skillId: 'docker', prereqId: 'git' },
  { skillId: 'linux', prereqId: 'git' },
  { skillId: 'ci-cd', prereqId: 'docker' },
  { skillId: 'cloud-fundamentals', prereqId: 'ci-cd' },
  { skillId: 'cloud-fundamentals', prereqId: 'linux' },
];

export const MOCK_ROLES = [
  {
    id: 'frontend-engineer',
    name: 'Frontend Engineer',
    description: 'Builds responsive, performant user interfaces, component design systems, and client-side applications.',
    requiredSkillIds: ['html-css', 'javascript', 'typescript', 'react', 'git', 'testing-frontend'],
  },
  {
    id: 'backend-engineer',
    name: 'Backend Engineer',
    description: 'Architects resilient server APIs, database schema models, authentication, and backend services.',
    requiredSkillIds: ['javascript', 'nodejs', 'express', 'rest-apis', 'sql', 'graph-db', 'git', 'docker'],
  },
  {
    id: 'fullstack-engineer',
    name: 'Full Stack Engineer',
    description: 'Master of end-to-end software delivery from responsive UIs down to databases and API infrastructure.',
    requiredSkillIds: ['javascript', 'typescript', 'react', 'nodejs', 'rest-apis', 'sql', 'git', 'docker'],
  },
  {
    id: 'data-scientist',
    name: 'Data Scientist',
    description: 'Extracts statistical insights from complex data, builds predictive models, and communicates findings.',
    requiredSkillIds: ['python', 'data-analysis', 'statistics', 'sql', 'machine-learning'],
  },
  {
    id: 'ml-engineer',
    name: 'Machine Learning Engineer',
    description: 'Deploys production machine learning pipelines, trains neural networks, and optimizes inference.',
    requiredSkillIds: ['python', 'data-analysis', 'statistics', 'machine-learning', 'deep-learning', 'docker'],
  },
  {
    id: 'devops-engineer',
    name: 'DevOps & Cloud Engineer',
    description: 'Automates CI/CD deployment pipelines, manages cloud infrastructure, and enforces system reliability.',
    requiredSkillIds: ['git', 'linux', 'docker', 'ci-cd', 'cloud-fundamentals'],
  },
];

export const MOCK_RESOURCES = [
  {
    id: 'res-mdn-js',
    title: 'MDN Web Docs: Modern JavaScript Guide',
    type: 'Documentation',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
    difficulty: 'Beginner',
    teachesSkillId: 'javascript',
  },
  {
    id: 'res-react-docs',
    title: 'React Official Interactive Documentation',
    type: 'Interactive Course',
    url: 'https://react.dev/learn',
    difficulty: 'Intermediate',
    teachesSkillId: 'react',
  },
  {
    id: 'res-ts-handbook',
    title: 'The TypeScript Handbook',
    type: 'Book / Docs',
    url: 'https://www.typescriptlang.org/docs/handbook/intro.html',
    difficulty: 'Intermediate',
    teachesSkillId: 'typescript',
  },
  {
    id: 'res-node-patterns',
    title: 'Node.js Design Patterns by Mario Casciaro',
    type: 'Book',
    url: 'https://www.nodejsdesignpatterns.com/',
    difficulty: 'Advanced',
    teachesSkillId: 'nodejs',
  },
  {
    id: 'res-cognodb-cypher',
    title: 'CognoDB & Cypher Graph Traversal Guide',
    type: 'Interactive Tutorial',
    url: 'https://neo4j.com/docs/cypher-manual/current/',
    difficulty: 'Intermediate',
    teachesSkillId: 'graph-db',
  },
  {
    id: 'res-python-data',
    title: 'Python for Data Analysis by Wes McKinney',
    type: 'Book',
    url: 'https://wesmckinney.com/book/',
    difficulty: 'Intermediate',
    teachesSkillId: 'data-analysis',
  },
  {
    id: 'res-fastai',
    title: 'Practical Deep Learning for Coders (Fast.ai)',
    type: 'Video Course',
    url: 'https://course.fast.ai/',
    difficulty: 'Advanced',
    teachesSkillId: 'deep-learning',
  },
  {
    id: 'res-docker-mastery',
    title: 'Docker Mastery: With Kubernetes & Swarm',
    type: 'Video Course',
    url: 'https://www.docker.com/get-started/',
    difficulty: 'Intermediate',
    teachesSkillId: 'docker',
  },
];

export const MOCK_PROJECTS = [
  {
    id: 'proj-portfolio',
    title: 'Responsive Developer Portfolio Website',
    description: 'Design and deploy a semantic, fully responsive portfolio showcasing interactive projects.',
    difficulty: 'Beginner',
    practicesSkillIds: ['html-css', 'javascript'],
  },
  {
    id: 'proj-kanban',
    title: 'Interactive Kanban Task Management App',
    description: 'Build a drag-and-drop task board in React & TypeScript with local persistence.',
    difficulty: 'Intermediate',
    practicesSkillIds: ['react', 'typescript'],
  },
  {
    id: 'proj-api-microservice',
    title: 'RESTful microservice with JWT Auth & SQL',
    description: 'Construct a production Node.js/Express API connected to PostgreSQL with rate-limiting.',
    difficulty: 'Intermediate',
    practicesSkillIds: ['nodejs', 'express', 'sql'],
  },
  {
    id: 'proj-churn-predictor',
    title: 'Customer Churn Machine Learning Model',
    description: 'Clean telemetry data in Pandas, train XGBoost classifier, and report feature importance.',
    difficulty: 'Advanced',
    practicesSkillIds: ['python', 'data-analysis', 'machine-learning'],
  },
  {
    id: 'proj-graph-explorer',
    title: 'PathGraph Cypher Relationship Explorer',
    description: 'Build a multi-hop graph traversal engine backed by CognoDB graph database.',
    difficulty: 'Advanced',
    practicesSkillIds: ['graph-db', 'react'],
  },
];
